### ISSUE TITLE
Feature - Add support to control the log level for the default logging setup.

### ISSUE THREAD

**Issue by u-ways** [u-ways/logging-http-client#11]
## Background

Within our default REQUEST and RESPONSE logging hook, the log level is set to INFO. However, there is no way to modify this via the client global configs.

https://github.com/u-ways/logging-http-client/blob/ac05cafb49f3801d81644720cce09e3af202671d/logging_http_client/http_session.py#L72-L77

https://github.com/u-ways/logging-http-client/blob/ac05cafb49f3801d81644720cce09e3af202671d/logging_http_client/http_session.py#L87-L89

## Requirements

We can provide a global config to enable the user to modify this default behavior:

https://github.com/u-ways/logging-http-client/blob/ac05cafb49f3801d81644720cce09e3af202671d/logging_http_client/logging_http_client_config_globals.py 

The value there can be set to `INFO` by default.

**Comment by KrinsKumar** [comment]
Hey Can I work on this? If yes please assign this to me so that I can start working on this

**Comment by u-ways** [comment]
Hello @KrinsKumar of course you can, I have assigned this to you. 

Please don't forget to:
- [ ] Add test coverage here: https://github.com/u-ways/logging-http-client/blob/main/tests/unit/test_logging_default_config.py
- [ ] Introduce a new sub-section in the documentation, here: https://github.com/u-ways/logging-http-client?tab=readme-ov-file#4-default-logging-configurations with the title: `iii. Changing the Default Log Level`

**Comment by KrinsKumar** [comment]
Hey @u-ways, Thanks for assigning this to me, I have started my work on this issue, I have added the global configs to tweak the log levels. I am yet to add the logic to set the log levels based on these global configs. I have some questions before I start: 

In the readme, I saw this basicConfig command being used on logging: Does this log level affect our global log level. 
```python
import logging
import logging_http_client as requests

# Basic logging configuration for demonstration purposes 
logging.basicConfig(
    level=logging.INFO,
    format='%(message)s - %(http)s'
)

# or does this get the preference
requests.set_logging_level(logging.DEBUG)

```

**Comment by u-ways** [comment]
@KrinsKumar 

```python
# Basic logging configuration for demonstration purposes 
logging.basicConfig(
    level=logging.INFO,
    format='%(message)s - %(http)s'
)
```

Creates a simple logger config set to info level logging.

By default our log level will be `INFO`, so that example in `README.md` will still be valid.

---

Setting our client log level to debug:

```python
requests.set_logging_level(logging.DEBUG)
```

Is what will (should) change the log level we use when the logging client is log a request/response.

**Comment by KrinsKumar** [comment]
This answers my question, thank you, so does that mean I can ignore the log level in the logger class, and only use INFO if user does not specify otherwise using `requests.set_logging_level()` function?.
Also one more questions, what should I see when I run this code?, for me, I dont see anything.
```python
import logging_http_client

logging_http_client.create().get('https://www.python.org')
```

**Comment by KrinsKumar** [comment]
Hey @u-ways, I have raised a PR, can you have a look and tell me if something needs to be changed?

**Comment by u-ways** [comment]
Hello @KrinsKumar , apologies I have been super busy with work, I have gone ahead and marked your contribution as accepted as it was great effort. I left some comments here: https://github.com/u-ways/logging-http-client/pull/21#pullrequestreview-2397305681
