### ISSUE TITLE
Documentation - Introduce docs.readthedocs.io for better readability

### ISSUE THREAD

**Issue by u-ways** [u-ways/logging-http-client#13]
### Background

Read the Docs simplifies software documentation by building, versioning, and hosting of your docs, automatically. Treating documentation like code keeps your team in the same tools, and your documentation up to date.

see: https://docs.readthedocs.io/en/stable/

### Requirements

- [ ] Follow this guide: https://docs.readthedocs.io/en/stable/tutorial/index.html
- [ ] If any steps require admin permissions document them in this issue, and I am happy to action.

**Comment by u-ways** [comment]
Hello @spyingcyclops , sounds great, thank you!

I have assigned this issue to you, please take your time reading the documentation linked in the description, and I will try to help you as much as possible as time allows. 🙂

**Comment by spyingcyclops** [comment]
Great, thank you! Just a heads up - we'll need to configure integration between RTD and GH so that future doc updates are sync'd. As the repo owner, I think you should also own the RTD account, if you agree. For now, though, I want to get the project running locally and check the docs & reqs.

**Comment by spyingcyclops** [comment]
Hi @u-ways-e 
So I've opened a PR:
https://github.com/u-ways/logging-http-client/pull/22

Details in the PR description, and I welcome your feedback!

Thanks!
